### ISSUE TITLE
Fix_formatting.py error

### ISSUE THREAD

**Issue by christophista** [victoria-mischley/PPIScreenML#2]
Hello

I am receiving the following error when running PPIscreenML. 

```python
Traceback (most recent call last):
  File "/mnt/nfs/clustersw/Debian/bookworm/ppiscreenml/20240701/PPIscreenML/get_classification.py", line 109, in <module>
    main(working_directory, args.protein1_chains_input, args.protein2_chains_input, csv_name, features_file_path)
  File "/mnt/nfs/clustersw/Debian/bookworm/ppiscreenml/20240701/PPIscreenML/get_classification.py", line 38, in main
    features_df = get_features.main(working_directory, protein1_chains_input, protein2_chains_input, csv_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/scistore07/clustersw/debian/bookworm/ppiscreenml/20240701/PPIscreenML/get_features.py", line 54, in main
    AF_fixed, AF_chainA, AF_chainB, fixed_json_numbering_dictionary = Fix_formatting.main(file_path, protein1_chains_input, protein2_chains_input)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/scistore07/clustersw/debian/bookworm/ppiscreenml/20240701/PPIscreenML/Fix_formatting.py", line 192, in main
    new_residue_number = combined_new_atomnum_resnum[atom_number]
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 11187
``` 

May I please ask for help on how to resolve the issue? 

Thank you in advance

**Comment by christophista** [comment]
I found the issue, all chains of a PDB file need to be specified in the parameters. 
I.e., if the PDB has chains A, B, C, and D, all four must be used for the parameters
--protein1_chains_input and --protein2_chains_input
e.g., as 
--protein1_chains_input and A B C --protein2_chains_input D

If that is specified somewhere in the documentation, I did not read it carefully, apologies.
